// <auto-generated />
namespace WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _16062020myMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_16062020myMig));
        
        string IMigrationMetadata.Id
        {
            get { return "202006161305492_16062020myMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
